export { FaPlus, FaRegEye, FaMinus, FaFacebookF, FaCloudDownloadAlt } from 'react-icons/fa';
export { FcGoogle } from 'react-icons/fc';
export { FiShoppingCart, FiUsers } from 'react-icons/fi';
export { IoLogoPolymer, IoMdSearch } from "react-icons/io";
export { IoDocumentText } from "react-icons/io5";
export { GrAdd } from 'react-icons/gr';
export { BiFilter, BiExit, BiSun, BiPencil, BiGridAlt } from 'react-icons/bi';
export { MdOutlineNightlight, MdOutlineChangeHistory, MdClose, MdLockOutline  } from 'react-icons/md';
export { BsKey, BsPaypal, BsInstagram, BsFillCreditCard2FrontFill, BsFillGrid3X3GapFill } from 'react-icons/bs';
export { AiFillDelete, AiOutlineMail, AiOutlineHome, AiOutlineFolderOpen, AiOutlineArrowLeft, AiOutlineTags, AiOutlineCreditCard, AiOutlineCloudUpload, AiOutlineSave } from 'react-icons/ai';